TAP version 13
# tst_Warnings
ok 1 - initTestCase()
ok 2 - testWarnings()
  ---
  extensions:
    messages:
    - severity: warning
      message: Warning
    - severity: warning
      message: Warning
    - severity: debug
      message: Debug
    - severity: debug
      message: Debug
    - severity: info
      message: Info
    - severity: info
      message: Info
    - severity: debug
      message: Baba
    - severity: debug
      message: Baba
    - severity: debug
      message: Bubublabla
    - severity: warning
      message: Babablabla
  ...
not ok 3 - testMissingWarnings()
  # inform: Did not receive message: "Warning0"
  # inform: Did not receive message: "Warning1"
  ---
  # Not all expected messages were received
  ...
not ok 4 - testMissingWarningsRegularExpression()
  # inform: Did not receive any message matching: "Warning\s\d"
  ---
  # Not all expected messages were received
  ...
not ok 5 - testMissingWarningsWithData(first row)
  # inform: Did not receive message: "Warning0"
  # inform: Did not receive message: "Warning1"
  ---
  # Not all expected messages were received
  ...
not ok 6 - testMissingWarningsWithData(second row)
  # inform: Did not receive message: "Warning0"
  # inform: Did not receive message: "Warning1"
  ---
  # Not all expected messages were received
  ...
not ok 7 - testFailOnWarnings()
  ---
  # Received a warning that resulted in a failure:
Ran out of cabbage!
  at: tst_Warnings::testFailOnWarnings() (qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp:0)
  file: qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp
  line: 0
  extensions:
    messages:
    - severity: warning
      message: Ran out of space!
  ...
# debug: Ran out of tortillas!
# info: Ran out of oil!
# warning: nope
not ok 7 - testFailOnWarnings()
  ---
  # Received a warning that resulted in a failure:
Ran out of biscuits!
  at: tst_Warnings::testFailOnWarnings() (qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp:0)
  file: qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp
  line: 0
  ...
not ok 7 - testFailOnWarnings()
  ---
  # Received a warning that resulted in a failure:
Running low on toothpaste!
  at: tst_Warnings::testFailOnWarnings() (qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp:0)
  file: qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp
  line: 0
  ...
# warning: Running low on flour!
# debug: Running low on toothpaste!
# info: Running low on toothpaste!
ok 8 - testFailOnWarningsCleared()
  ---
  extensions:
    messages:
    - severity: warning
      message: Ran out of muffins!
  ...
not ok 9 - testFailOnWarningsWithData(warning1)
  ---
  # Received a warning that resulted in a failure:
warning1
  at: tst_Warnings::testFailOnWarningsWithData() (qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp:0)
  file: qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp
  line: 0
  ...
# warning: warning2
# warning: warning3
not ok 10 - testFailOnWarningsWithData(warning2)
  ---
  # Received a warning that resulted in a failure:
warning2
  at: tst_Warnings::testFailOnWarningsWithData() (qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp:0)
  file: qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp
  line: 0
  extensions:
    messages:
    - severity: warning
      message: warning1
  ...
# warning: warning3
not ok 11 - testFailOnWarningsWithData(warning3)
  ---
  # Received a warning that resulted in a failure:
warning3
  at: tst_Warnings::testFailOnWarningsWithData() (qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp:0)
  file: qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp
  line: 0
  extensions:
    messages:
    - severity: warning
      message: warning1
    - severity: warning
      message: warning2
  ...
not ok 12 - testFailOnWarningsFailInHelper()
  ---
  # This failure message should be printed but not cause the test to abort
  at: tst_Warnings::testFailOnWarningsFailInHelper() (qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp:0)
  file: qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp
  line: 0
  ...
not ok 12 - testFailOnWarningsFailInHelper()
  ---
  # Received a warning that resulted in a failure:
Ran out of cabbage!
  at: tst_Warnings::testFailOnWarningsFailInHelper() (qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp:0)
  file: qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp
  line: 0
  ...
not ok 12 - testFailOnWarningsFailInHelper()
  ---
  # My cabbage! :(
  at: tst_Warnings::testFailOnWarningsFailInHelper() (qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp:0)
  file: qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp
  line: 0
  ...
not ok 13 - testFailOnWarningsThenSkip()
  ---
  # Received a warning that resulted in a failure:
Ran out of cabbage!
  at: tst_Warnings::testFailOnWarningsThenSkip() (qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp:0)
  file: qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp
  line: 0
  ...
ok 13 - testFailOnWarningsThenSkip() # SKIP My cabbage! :(
ok 14 - testFailOnWarningsAndIgnoreWarnings()
not ok 15 - testFailOnTemporaryObjectDestruction()
  ---
  # Received a warning that resulted in a failure:
Running low on toothpaste!
  at: tst_Warnings::testFailOnTemporaryObjectDestruction() (qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp:0)
  file: qtbase/tests/auto/testlib/selftests/warnings/tst_warnings.cpp
  line: 0
  ...
ok 16 - cleanupTestCase()
1..16
# tests 16
# pass 5
# fail 11
