<?xml version="1.0" encoding="UTF-8" ?>
<testsuite name="tst_JUnit" timestamp="@TEST_START_TIME@" hostname="@HOSTNAME@" tests="9" failures="3" errors="0" skipped="1" time="@TEST_DURATION@">
  <properties>
    <property name="QTestVersion" value="@INSERT_QT_VERSION_HERE@"/>
    <property name="QtVersion" value="@INSERT_QT_VERSION_HERE@"/>
    <property name="QtBuild" value=""/>
  </properties>
  <testcase name="initTestCase" classname="tst_JUnit" time="@TEST_DURATION@"/>
  <testcase name="testFunc1" classname="tst_JUnit" time="@TEST_DURATION@">
    <system-err>
      <![CDATA[just a qWarning() !]]>
    </system-err>
  </testcase>
  <testcase name="testFunc2" classname="tst_JUnit" time="@TEST_DURATION@">
    <failure type="fail" message="Compared values are not the same">
      <![CDATA[   Actual   (2): 2
   Expected (3): 3]]>
    </failure>
    <system-out>
      <![CDATA[a qDebug() call with comment-ending stuff -->]]>
    </system-out>
  </testcase>
  <testcase name="testFunc3" classname="tst_JUnit" time="@TEST_DURATION@">
    <skipped message="skipping this function!"/>
  </testcase>
  <testcase name="testFunc4" classname="tst_JUnit" time="@TEST_DURATION@">
    <failure type="fail" message="a forced failure!"/>
  </testcase>
  <testcase name="testFunc5" classname="tst_JUnit" time="@TEST_DURATION@">
    <system-out>
      <![CDATA[this failure is expected]]>
    </system-out>
  </testcase>
  <testcase name="testFunc6" classname="tst_JUnit" time="@TEST_DURATION@">
    <system-out>
      <![CDATA[this failure is also expected]]>
    </system-out>
  </testcase>
  <testcase name="testFunc7" classname="tst_JUnit" time="@TEST_DURATION@">
    <failure type="xpass" message="&apos;true&apos; returned TRUE unexpectedly. ()"/>
  </testcase>
  <testcase name="cleanupTestCase" classname="tst_JUnit" time="@TEST_DURATION@"/>
</testsuite>
